### ISSUE TITLE
Copy icon overflow

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-common#20]
The copy to clipboard icon is outside the box if there is a lot of text eg. with handle 11234/LRT-1478
![image](https://cloud.githubusercontent.com/assets/1842385/9605384/ba547630-50bd-11e5-96a7-fbc98d31bbd9.png)

**Comment by m1ch4ls** [comment]
I can't reproduce this. Can you add Browser + OS + resolution?

**Comment by kosarko** [comment]
https://ufal-point-dev.ms.mff.cuni.cz/repository/xmlui/handle/11234/LRT-1478
chrome Version 37.0.2062.120 (64-bit) on linux
1920x1200

**Comment by m1ch4ls** [comment]
I don't have any FULL HD monitor :cry: and it doesn't show up in Chrome screen emulation. 

Just a note - the current version of Chrome is 44. Can you try it on 44?

**Comment by kosarko** [comment]
tried it at home with Chrome Version 46.0.2490.22 beta-m (64-bit) on windows 7 with 1920x1080. seems fine.
I am not sure I'll be able to get the latest version on the 1920x1200 linux screen. Let you know on monday

**Comment by kosarko** [comment]
Updated chrome on the linux machine. Looks ok

**Comment by m1ch4ls** [comment]
Still wrong for Webkit browsers...
