### ISSUE TITLE
localize refbox

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-common#22]
remove hardcoded strings
create czech translation
come with a way to switch the languages (eg. when the box is .shown it is passed a language parameter)

**Comment by m1ch4ls** [comment]
We can now do this easily using Webpack's localization plugin. Let me know when this has a :top: priority.

**Comment by kosarko** [comment]
Generating locale/lindat-refbox.js (e.g. `public/js/cs/lindat-refbox.js`) see 2cd9b7829398de90a1ea25e9062456638e30f34d and fe29c31baad83c306949c855670421c4a8a778dd
