### ISSUE TITLE
localising "Please use the following text to cite ..."

### ISSUE THREAD

**Issue by cyplas** [ufal/lindat-common#31]
In the releases branch, the string "Please use the following text to cite this item or export to a predefined format" appears deep in the refbox and angular javascript files. It would be nice if this string were customisable, like the header or footer, without having to build ourselves.

**Comment by kosarko** [comment]
Right now I'd rather not touch how the localisation is done...
We can either add non minified versions of the javascript, so it's bit easier to find and replace.
Or if you could provide a translation as is in https://github.com/ufal/lindat-common/blob/master/src/refbox/lang/cs.json we could add that. You'd then include from a different directory, eg. https://github.com/ufal/lindat-common/tree/releases/public/js/cs
These translations are not built into the angular files at the moment, are you using those?

**Comment by cyplas** [comment]
Adding a sl.json translation seems easiest and most sensible to me, thank you. We will post one. 

Will we then still need to configure something so that it is used, or will it be used automatically if locale=sl? If I add "?locale-attribute=cs" to a URL with a lindat-dspace refbox, it still shows the English version, although I imagine that might just be because we don't have "cs" amongst our supported.locales in lindat-dspace.

We are not using angular.

**Comment by kosarko** [comment]
> Will we then still need to configure something so that it is used, or will it be used automatically if locale=sl? If I add "?locale-attribute=cs" to a URL with a lindat-dspace refbox, it still shows the English version, although I imagine that might just be because we don't have "cs" amongst our supported.locales in lindat-dspace.

I'll have to do one more change in https://github.com/ufal/lindat-dspace/blob/lindat/dspace-xmlui/src/main/webapp/themes/UFAL/lib/xsl/core/page-structure.xsl#L547 again the cs is hardcoded there. And yes I believe locales that are not configured are ignored.

**Comment by cyplas** [comment]
Below is the Slovene translation.  It would be great if you could include this in the next common-theme release, even if you don't get around to adapting page-structure.xsl yet (as we can do that for now in an overlay).

{
"Please use the following text to cite this item or export to a predefined format:":
"Za citiranje vnosa uporabite naslednjo referenco ali jo izvozite v prednastavljeno obliko:",
"This resource is also integrated in following services:":
"Ta vir je integriran tudi v naslednje storitve:",
"Share:": "Delite:"
}

**Comment by kosarko** [comment]
should be there https://github.com/ufal/lindat-common/blob/releases/public/js/si/lindat-refbox.js

**Comment by cyplas** [comment]
Great, thank you! The only thing is that it should be sl, not si (I think this is like cs and cz in your case).

**Comment by kosarko** [comment]
> Great, thank you! The only thing is that it should be sl, not si (I think this is like cs and cz in your case).

Ok, haven't realized that. https://github.com/ufal/lindat-common/tree/releases/public/js/sl

**Comment by cyplas** [comment]
It's working, thanks :)
