### ISSUE TITLE
BibTeX accented characters escaping

### ISSUE THREAD

**Issue by dan-zeman** [ufal/lindat-common#35]
The Bibtex provided in citationbox converts known accented characters to corresponding LaTeX escape sequences. However, it does not properly handle accented "i" (and perhaps also "j") where the dot should be removed first, then the new accent added. Example (e.g. in http://hdl.handle.net/11234/1-1983) is i with macron (Grūzītis, Normunds). The current BibTeX has

Gr{\=
u}z{\=i}tis, Normunds

while it should be

Gr{\=u}z{\={\i}}tis, Normunds

**Comment by kosarko** [comment]
Thanks, the mapping is defined by hand (as we haven't found a library that would map unicode to TeX coded chars), so there might be mistakes and missing mappings.
For example there's no mapping for "j", do you have some kind of table with these mappings?

If you are interested in what we have check https://github.com/ufal/clarin-dspace/blob/clarin/dspace-oai/src/main/java/cz/cuni/mff/ufal/utils/BibtexUtil.java#L129
So probably none of the accented "i" are correct

**Comment by dan-zeman** [comment]
I suspect that accented "j" is very rare, especially in personal names. One example would be

"ĵ{\\^{\\j}}"

but I have not really met it in citations.
When we are at it, here are some other suggestions:

"ğ{\\u g}"
"ı{\\i}", "ị{\\d i}"
"ņ{\\c n}"
"ỳ{\\`y}", "ŷ{\\^y}", "ỹ{\\~y}"

**Comment by dan-zeman** [comment]
Seems we also need an escape for "Nguyễn". But I don't know what the proper LaTeX solution is.

**Comment by dan-zeman** [comment]
Here we go, thanks @dseddah for the link: http://texdoc.net/texmf-dist/doc/generic/vntex/vn-min.pdf

**Comment by dseddah** [comment]
not all of them works with my latex version though (the \uhorn for example). I'm using mactex 2015 (I know I've should have upgraded long ago so don't take this report as gold.)

while I'm at it, here's my converted version of the UD2.0 bib entry but there's still errors when I compile so I gave up for tonight (problem comes from some vietnamese chars, should be used with \usepackage[T1,5]{encoding} but I'm having errors.

@misc{ud20data,
	Author = {Nivre, Joakim and Agi{\'c}, {\v Z}eljko and Ahrenberg, Lars and Aranzabe, Maria Jesus and Asahara, Masayuki and Atutxa, Aitziber and Ballesteros, Miguel and Bauer, John and Bengoetxea, Kepa and Bhat, Riyaz Ahmad and Bick, Eckhard and Bosco, Cristina and Bouma, Gosse and Bowman, Sam and Candito, Marie and Cebiro{\u g}lu Eryi{\u g}it, G{\"u}l{\c s}en and Celano, Giuseppe G. A. and Chalub, Fabricio and Choi, Jinho and {\c C}{\"o}ltekin, {\c C}a{\u g}rı and Connor, Miriam and Davidson, Elizabeth and de Marneffe, Marie-Catherine and de Paiva, Valeria and Diaz de Ilarraza, Arantza and Dobrovoljc, Kaja and Dozat, Timothy and Droganova, Kira and Dwivedi, Puneet and Eli, Marhaba and Erjavec, Toma{\v z} and Farkas, Rich{\'a}rd and Foster, Jennifer and Freitas, Cl{\'a}udia and Gajdo{\v s}ov{\'a}, Katar{\'\i}na and Galbraith, Daniel and Garcia, Marcos and Ginter, Filip and Goenaga, Iakes and Gojenola, Koldo and G{\"o}kırmak, Memduh and Goldberg, Yoav and G{\'o}mez Guinovart, Xavier and Gonz{\'a}les Saavedra, Berta and Grioni, Matias and Gr{\=u}z{\=\i}tis, Normunds and Guillaume, Bruno and Habash, Nizar and Haji{\v c}, Jan and H{\`a} M{\~y}, Linh and Haug, Dag and Hladk{\'a}, Barbora and Hohle, Petter and Ion, Radu and Irimia, Elena and Johannsen, Anders and J{\o}rgensen, Fredrik and Ka{\c s}ıkara, H{\"u}ner and Kanayama, Hiroshi and Kanerva, Jenna and Kotsyba, Natalia and Krek, Simon and Laippala, Veronika and L{\^e} H{\`\ocircumflex}ng, Ph{\ohorn}ng and Lenci, Alessandro and Ljube{\v s}i{\'c}, Nikola and Lyashevskaya, Olga and Lynn, Teresa and Makazhanov, Aibek and Manning, Christopher and M{\u a}r{\u a}nduc, C{\u a}t{\u a}lina and Mare{\v c}ek, David and Mart{\'\i}nez Alonso, H{\'e}ctor and Martins, Andr{\'e} and Ma{\v s}ek, Jan and Matsumoto, Yuji and {McDonald}, Ryan and Missil{\"a}, Anna and Mititelu, Verginica and Miyao, Yusuke and Montemagni, Simonetta and More, Amir and Mori, Shunsuke and Moskalevskyi, Bohdan and Muischnek, Kadri and Mustafina, Nina and M{\"u}{\"u}risep, Kaili and Nguy{\~\ecircumflex}n Th{\d i}, L{\uhorn}{\ohorn}ng and Nguy{\~\ecircumflex}n Th{\d i} Minh, Huy{\`\ecircumflex}n and Nikolaev, Vitaly and Nurmi, Hanna and Ojala, Stina and Osenova, Petya and {\O}vrelid, Lilja and Pascual, Elena and Passarotti, Marco and Perez, Cenel-Augusto and Perrier, Guy and Petrov, Slav and Piitulainen, Jussi and Plank, Barbara and Popel, Martin and Pretkalni{\c n}a, Lauma and Prokopidis, Prokopis and Puolakainen, Tiina and Pyysalo, Sampo and Rademaker, Alexandre and Ramasamy, Loganathan and Real, Livy and Rituma, Laura and Rosa, Rudolf and Saleh, Shadi and Sanguinetti, Manuela and Saul{\=\i}te, Baiba and Schuster, Sebastian and Seddah, Djam{\'e} and Seeker, Wolfgang and Seraji, Mojgan and Shakurova, Lena and Shen, Mo and Sichinava, Dmitry and Silveira, Natalia and Simi, Maria and Simionescu, Radu and Simk{\'o}, Katalin and {\v S}imkov{\'a}, M{\'a}ria and Simov, Kiril and Smith, Aaron and Suhr, Alane and Sulubacak, Umut and Sz{\'a}nt{\'o}, Zsolt and Taji, Dima and Tanaka, Takaaki and Tsarfaty, Reut and Tyers, Francis and Uematsu, Sumire and Uria, Larraitz and van Noord, Gertjan and Varga, Viktor and Vincze, Veronika and Washington, Jonathan North and {\v Z}abokrtsk{\'y}, Zden{\v e}k and Zeldes, Amir and Zeman, Daniel and Zhu, Hanzhi},
	Copyright = {Licence Universal Dependencies v2.0},
	Date-Added = {2017-10-02 22:45:00 +0000},
	Date-Modified = {2017-10-02 22:45:20 +0000},
	Note = {{LINDAT}/{CLARIN} digital library at the Institute of Formal and Applied Linguistics, Charles University},
	Title = {Universal Dependencies 2.0},
	Url = {http://hdl.handle.net/11234/1-1983},
	Year = {2017},
	Bdsk-Url-1 = {http://hdl.handle.net/11234/1-1983}}

**Comment by kosarko** [comment]
deployed a fix for what was fixable without libraries. see the comments in ufal/clarin-dspace#788.

closing
