### ISSUE TITLE
Proper institution name

### ISSUE THREAD

**Issue by e-bej** [ufal/lindat-common#38]
Feature request: The required minimal form for a publisher name if it is ÚFAL is:

      Charles University, Faculty of Mathematics and Physics

(and it can continue with "Institute of Formal and Applied Linguistics", if you want).

When start typing Charles in item submission -- not even one of the suggestions showed is correct.
(And I am not speaking about obsolete "in Prague" suffix.)
Of course, it is not a fault of LINDAT repository, but it would be quite useful to test this field and insist on proper publisher name for MFF data.

(BTW, all 151 out of 151 items with publisher containing "UFAL" violate dean's regulation.)

**Comment by kosarko** [comment]
updated the publisher metadata in repository
