### ISSUE TITLE
update project identifier in the footer

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-common#42]
LINDAT has been project LM2015071 for a while now :-)

**Comment by hajic** [comment]
Please use both LM2010013 and LM2015071 as well as the OP VVV, e.g. like this in the parenthesis:
 (LM2015071 and CZ.02.1.01/0.0/0.0/16_013/0001781; formerly: LM2010013)

**Comment by hajic** [comment]
Sorry clicked the wrong button. Reopened now.

**Comment by stranak** [comment]
Please review my pull request and pick "Request Changes" there, with your original comment. I will fix it immediately.

--p

**Comment by stranak** [comment]
OK, no need, I updated the pull request.
