### ISSUE TITLE
Superfluous backslashes in Bibtex

### ISSUE THREAD

**Issue by dan-zeman** [ufal/lindat-common#44]
There is a bug in escaping accented capital Latin letters when the official Bibtex entry of a Lindat item is generated. There is always one extra backslash. In Latex, the result is interpreted as a line break, and the character representing the accent is then interpreted following its own semantics.

Example: Universal Dependencies 2.1 (https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-2515). The second author is escaped as

    Agi{\'c}, {\\v Z}eljko

while it should be only

    Agi{\'c}, {\v Z}eljko

Several other authors in the same Bibtex item are affected, and the error also appears in the note field (

    {{\\'U}FAL}

). The error does not seem to occur with lowercase letters.

**Comment by dan-zeman** [comment]
This is my version of the reference to UD 2.1. (It starts \@languageresource because of LREC, you probably want to generate \@misc.)

    @LanguageResource{ud21,
     title = {Universal Dependencies 2.1},
     author = {Nivre, Joakim and Agi{\'c}, {\v Z}eljko and Ahrenberg, Lars and Antonsen, Lene and Aranzabe, Maria Jesus and Asahara, Masayuki and Ateyah, Luma and Attia, Mohammed and Atutxa, Aitziber and Augustinus, Liesbeth and Badmaeva, Elena and Ballesteros, Miguel and Banerjee, Esha and Bank, Sebastian and Barbu Mititelu, Verginica and Bauer, John and Bengoetxea, Kepa and Bhat, Riyaz Ahmad and Bick, Eckhard and Bobicev, Victoria and B{\"o}rstell, Carl and Bosco, Cristina and Bouma, Gosse and Bowman, Sam and Burchardt, Aljoscha and Candito, Marie and Caron, Gauthier and Cebiro{\u g}lu Eryi{\u g}it, G{\"u}l{\c s}en and Celano, Giuseppe G. A. and Cetin, Savas and Chalub, Fabricio and Choi, Jinho and Cinkov{\'a}, Silvie and {\c C}{\"o}ltekin, {\c C}a{\u g}r{\i} and Connor, Miriam and Davidson, Elizabeth and de Marneffe, Marie-Catherine and de Paiva, Valeria and Diaz de Ilarraza, Arantza and Dirix, Peter and Dobrovoljc, Kaja and Dozat, Timothy and Droganova, Kira and Dwivedi, Puneet and Eli, Marhaba and Elkahky, Ali and Erjavec, Toma{\v z} and Farkas, Rich{\'a}rd and Fernandez Alcalde, Hector and Foster, Jennifer and Freitas, Cl{\'a}udia and Gajdo{\v s}ov{\'a}, Katar{\'{\i}}na and Galbraith, Daniel and Garcia, Marcos and G{\"a}rdenfors, Moa and Gerdes, Kim and Ginter, Filip and Goenaga, Iakes and Gojenola, Koldo and G{\"o}k{\i}rmak, Memduh and Goldberg, Yoav and G{\'o}mez Guinovart, Xavier and Gonz{\'a}les Saavedra, Berta and Grioni, Matias and Gr{\=u}z{\={\i}}tis, Normunds and Guillaume, Bruno and Habash, Nizar and Haji{\v c}, Jan and Haji{\v c} jr., Jan and H{\`a} M{\~y}, Linh and Harris, Kim and Haug, Dag and Hladk{\'a}, Barbora and Hlav{\'a}{\v c}ov{\'a}, Jaroslava and Hociung, Florinel and Hohle, Petter and Ion, Radu and Irimia, Elena and Jel{\'{\i}}nek, Tom{\'a}{\v s} and Johannsen, Anders and J{\o}rgensen, Fredrik and Ka{\c s}{\i}kara, H{\"u}ner and Kanayama, Hiroshi and Kanerva, Jenna and Kayadelen, Tolga and Kettnerov{\'a}, V{\'a}clava and Kirchner, Jesse and Kotsyba, Natalia and Krek, Simon and Laippala, Veronika and Lambertino, Lorenzo and Lando, Tatiana and Lee, John and L{\^e} H{\`{\^o}}ng, Phương and Lenci, Alessandro and Lertpradit, Saran and Leung, Herman and Li, Cheuk Ying and Li, Josie and Li, Keying and Ljube{\v s}i{\'c}, Nikola and Loginova, Olga and Lyashevskaya, Olga and Lynn, Teresa and Macketanz, Vivien and Makazhanov, Aibek and Mandl, Michael and Manning, Christopher and M{\u a}r{\u a}nduc, C{\u a}t{\u a}lina and Mare{\v c}ek, David and Marheinecke, Katrin and Mart{\'{\i}}nez Alonso, H{\'e}ctor and Martins, Andr{\'e} and Ma{\v s}ek, Jan and Matsumoto, Yuji and {McDonald}, Ryan and Mendon{\c c}a, Gustavo and Miekka, Niko and Missil{\"a}, Anna and Mititelu, C{\u a}t{\u a}lin and Miyao, Yusuke and Montemagni, Simonetta and More, Amir and Moreno Romero, Laura and Mori, Shinsuke and Moskalevskyi, Bohdan and Muischnek, Kadri and M{\"u}{\"u}risep, Kaili and Nainwani, Pinkey and Nedoluzhko, Anna and Ne{\v s}pore-B{\=e}rzkalne, Gunta and Nguy{\~{\^e}}n Th{\d i}, Lương and Nguy{\~{\^e}}n Th{\d i} Minh, Huy{\`{\^e}}n and Nikolaev, Vitaly and Nurmi, Hanna and Ojala, Stina and Osenova, Petya and {\"O}stling, Robert and {\O}vrelid, Lilja and Pascual, Elena and Passarotti, Marco and Perez, Cenel-Augusto and Perrier, Guy and Petrov, Slav and Piitulainen, Jussi and Pitler, Emily and Plank, Barbara and Popel, Martin and Pretkalni{\c n}a, Lauma and Prokopidis, Prokopis and Puolakainen, Tiina and Pyysalo, Sampo and Rademaker, Alexandre and Ramasamy, Loganathan and Rama, Taraka and Ravishankar, Vinit and Real, Livy and Reddy, Siva and Rehm, Georg and Rinaldi, Larissa and Rituma, Laura and Romanenko, Mykhailo and Rosa, Rudolf and Rovati, Davide and Sagot, Beno{\^{\i}}t and Saleh, Shadi and Samard{\v z}i{\'c}, Tanja and Sanguinetti, Manuela and Saul{\={\i}}te, Baiba and Schuster, Sebastian and Seddah, Djam{\'e} and Seeker, Wolfgang and Seraji, Mojgan and Shen, Mo and Shimada, Atsuko and Sichinava, Dmitry and Silveira, Natalia and Simi, Maria and Simionescu, Radu and Simk{\'o}, Katalin and {\v S}imkov{\'a}, M{\'a}ria and Simov, Kiril and Smith, Aaron and Stella, Antonio and Straka, Milan and Strnadov{\'a}, Jana and Suhr, Alane and Sulubacak, Umut and Sz{\'a}nt{\'o}, Zsolt and Taji, Dima and Tanaka, Takaaki and Trosterud, Trond and Trukhina, Anna and Tsarfaty, Reut and Tyers, Francis and Uematsu, Sumire and Ure{\v s}ov{\'a}, Zde{\v n}ka and Uria, Larraitz and Uszkoreit, Hans and Vajjala, Sowmya and van Niekerk, Daniel and van Noord, Gertjan and Varga, Viktor and Villemonte de la Clergerie, Eric and Vincze, Veronika and Wallin, Lars and Washington, Jonathan North and Wir{\'e}n, Mats and Wong, Tak-sum and Yu, Zhuoran and {\v Z}abokrtsk{\'y}, Zden{\v e}k and Zeldes, Amir and Zeman, Daniel and Zhu, Hanzhi},
     url = {http://hdl.handle.net/11234/1-2515},
     note = {{LINDAT}/{CLARIN} digital library at the Institute of Formal and Applied Linguistics ({{\'U}FAL}), Faculty of Mathematics and Physics, Charles University},
     copyright = {Licence Universal Dependencies v2.1},
     year = {2017}
    }

**Comment by kosarko** [comment]
will be fixed in the next release
